# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SecureBeam Core' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SecureBeam Core
  pod 'CryptoSwift', '~> 0.8'
  target 'SecureBeam CoreTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SecureBeam CoreUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
